#!/bin/bash
START_PATH="`(pwd)`"

MY_PATH="`dirname \"$0\"`"              # relative
MY_PATH="`( cd \"$MY_PATH\" && pwd )`"  # absolutized and normalized
if [ -z "$MY_PATH" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo Script failure locating script path.
  exit 1  # fail
fi

cd $START_PATH

exec java -jar $MY_PATH/Trng.jar "$@"



